---
title: "Class One (Answers): Computational Biology Reading Group"
author: "Your name"
date: "Oct 20, 2021"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Hey! I am a comment, how are you?

# Run the following line to install all requires packages
# install.packages("tidyverse")
library(tidyverse) 
```

# R Basics

## R can be used as a glorified calculator  

```{r calc}
# arithmetic operations
2 + 3 * 5

# natural log of 10
log(10)

# useful base R functions
sqrt(256)
abs(5-10)
```

## Data structures 

### Vectors

```{r vectors}
# vector
vec <- c(1, -2, 10, -4, 5)

# operations on the vector
abs(vec)
vec^2

# how many elements are in my vector?
length(vec)

# subsetting a vector
# select just the first three elements
vec[1:3]

# how to look up what a function does
?abs
```

### Matrices

```{r matrices}
# create a matrix
matrix(c(1,3,2,5,-1,2,2,3,9), nrow = 3)

# assign this matrix to an object called "m"
m <- matrix(c(1,3,2,5,-1,2,2,3,9), nrow = 3)
m

# how many rows and columns does my matrix contain?
dim(m)

# subsetting a matrix
# select only the elements of the first row
m[1, ]

# select only the elements of the first column
m[, 1]

# select ALL the elements of the first two rows
m[1:2 ,]
```

### Data frames

```{r dataframe}
# create a data frame
chr <- c("chr1", "chr1", "chr2", "chr2")
strand <- c("-", "-", "+", "+")
start <- c(200, 4000, 100, 400)
end <- c(250, 410, 200, 450)
mydata <- data.frame(chr, start, end, strand)

# select columns 1 and 3
# base R way
mydata[ , c(1, 3)]

# the dplyr way
select(mydata, c(1, 3))

# Introducing the pipe
mydata %>% 
  select(c(1, 3))

# Only choose rows corresponding to chr1
mydata %>% 
  filter(chr == "chr1")

# Only choose rows corresponding to chr1 AND only keep columns 1 and 3
mydata %>% 
  filter(chr == "chr1") %>% 
  select(c(1, 3))

# assign the output of the above to a new object
mydata_2 <- mydata %>% 
  filter(chr == "chr1") %>% 
  select(c(1, 3))

# What would this look like WITHOUT the pipe?
select(filter(mydata, chr == "chr1"), c(1, 3))

# NOTE: dplyr only works with data frames and NOT matrices!
```

### Importing Data

```{r data-import}
golub_subjects <- readr::read_csv("https://raw.githubusercontent.com/BAREJAA/website_for_john/master/datasets/golub_kaggle/golub_subjects.csv")
```

