---
title: "Computational Biology Reading Group"
subtitle: "<br/>CBRG"
author: ""
institute: "DMPI"
date: ""
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(tidyverse)
library(kableExtra)
library(xaringanExtra)
library(janitor)
library(xaringanthemer)

```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#00539B",
  header_font_google = google_font("Adobe Caslon"),
  text_font_google   = google_font("Adobe Caslon", "300", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```

```{r xaringanExtra-freezeframe, echo = FALSE, message = FALSE}
options(htmltools.dir.version = FALSE)
xaringanExtra::use_freezeframe()
```

```{r xaringanExtra-clipboard, echo=FALSE}
xaringanExtra::use_clipboard()
```

```{r xaringan-panelset, echo=FALSE}
xaringanExtra::use_panelset()
```

---
class: center, middle

# Welcome! 

---
# Goals of the reading group  

--
- Learn how to use R to answer questions of biological interest 

--
- Build a community! 

--
- Create a repository of code/data/recordings  

---
# Install R and RStudio

Install R - https://www.r-project.org

Install RStudio - https://www.rstudio.com/products/rstudio/download/
---

```{r, echo = FALSE, fig.cap = "Computational Genomics with R by Altuna Akalin"}
knitr::include_url("http://compgenomr.github.io/book/")
```

---
```{r, echo = FALSE, fig.cap = "Omics Data Analysis by Laurent Gatto"}
knitr::include_url("https://uclouvain-cbio.github.io/WSBIM2122/index.html")
```

---
# For today 

- Create a project  
- Install the CBRG package 
- Do some exercises!  

